import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';


const config: Config = {
  title: 'Today I Learned',
  tagline: '매일은 아니더라도 꾸준하게',
  favicon: 'img/favicon.ico',

  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  url: 'https://luke0408.github.io',
  baseUrl: '/TIL/',
  projectName: 'TIL', // Usually your repo name.
  organizationName: 'luke0408', // Usually your GitHub org/user name.

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'ko',
    locales: ['ko', 'en'],
  },

  // markdown
  markdown: {
    mermaid: true,
  },
  themes: ['@docusaurus/theme-mermaid'],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/docusaurus-social-card.jpg',
    navbar: {
      title: 'luke0408/TIL',
      logo: {
        alt: 'luke0408',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: './',
        }
      ],
    },
    mermaid: {
      options: {
        theme: 'neutral',
        look: 'handDrawn',
        elk: {
          mergeEdges: true,
        }
      }
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Community',
          items: [
            {
              label: 'Github',
              href: 'https://github.com/luke0408',
            },
            {
              label: 'LinkedIn',
              href: 'https://www.linkedin.com/in/sunkyu-choi-59466527b/',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} My Project, Inc. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
